### ISSUE TITLE
Error when loading the initial state from vtu-file

### ISSUE THREAD

**Issue by Falconcp** [R-Hertel/tetmag#1]
Hi,

I've had some problems reproducing the third example.

I have relaxed the configuration and obtained the VTU file. However, when I load it into the dynamic simulation, it doesn't seem to work, since in the log file it appears that the average magnetization is <M> = 0 0 1.  In paraview I observe a vortex state.

**Comment by R-Hertel** [comment]
In the dynamic simulation, the user should provide the name of the VTU input file in the `simulation.cfg` file using a line of the type:
`initial state = fromfile_<inputfile_in_vtu_format>`

In example #3, as mentioned in the documentation, the input file is called `sp_stt_vortex.vtu`, so we use the line `initial state = fromfile_sp_stt_vortex.vtu`.  If `tetmag` doesn't find the input file specified after `fromfile_`, it will complain. However, if the prefix `fromfile_` is missing or mistyped, it will not recognize that it should even look for an input file and instead start the simulation with the default configuration, which is a homogeneous state magnetized along the z-direction. Please verify whether the `initial state` input line in your `simulation.cfg` file is correct.

**Comment by Falconcp** [comment]
thank you very much, it worked.

**Comment by Falconcp** [comment]
Hi, 

In this version of tetmag is it possible to implement a electric current that depends on the coordinates?. I have seen that it is only possible to define the current based on the theta and phi angles.

**Comment by R-Hertel** [comment]
The current version of tetmag supports only homogeneous current density distributions with the flow direction defined by the angles theta and phi. I intend to implement the option to use a position-dependent current density distribution in future releases.

**Comment by R-Hertel** [comment]
The current version of tetmag supports only homogeneous current density distributions with the flow direction defined by the angles theta and phi. I intend to implement the option to use a position-dependent current density distribution in future releases.
